IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep1' AND COLUMN_NAME='Bonus_Others')
ALTER TABLE [xPayRep1] ADD [Bonus_Others] [money] NULL CONSTRAINT [DF_xPayRep1_Bonus_Others]  DEFAULT ((0))