IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep2' AND COLUMN_NAME='Bonus_Others')
ALTER TABLE [xPayRep2] ADD [Bonus_Others] [money] NULL CONSTRAINT [DF_xPayRep2_Bonus_Others]  DEFAULT ((0))
