IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep3' AND COLUMN_NAME='Bonus_Others')
ALTER TABLE [xPayRep3] ADD [Bonus_Others] [money] NULL CONSTRAINT [DF_xPayRep3_Bonus_Others]  DEFAULT ((0))