IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='dtaPayrollProcess' AND COLUMN_NAME='MPF_EE')
ALTER TABLE [dtaPayrollProcess] ADD [MPF_EE] [smallmoney] NULL CONSTRAINT [DF_dtaPayrollProcess_MPF_EE]  DEFAULT ((0))

IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='dtaPayrollProcess' AND COLUMN_NAME='MPF_ER')
ALTER TABLE [dtaPayrollProcess] ADD [MPF_ER] [smallmoney] NULL CONSTRAINT [DF_dtaPayrollProcess_MPF_ER]  DEFAULT ((0))
