IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='dtaTemp' AND COLUMN_NAME='MPF_EE')
ALTER TABLE [dtaTemp] ADD [MPF_EE] [smallmoney] NULL CONSTRAINT [DF_dtaTemp_MPF_EE]  DEFAULT ((0))

IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='dtaTemp' AND COLUMN_NAME='MPF_ER')
ALTER TABLE [dtaTemp] ADD [MPF_ER] [smallmoney] NULL CONSTRAINT [DF_dtaTemp_MPF_ER]  DEFAULT ((0))
