IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep1' AND COLUMN_NAME='MPF_EE')
ALTER TABLE [xPayRep1] ADD [MPF_EE] [smallmoney] NULL CONSTRAINT [DF_xPayRep1_MPF_EE]  DEFAULT ((0))

IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep1' AND COLUMN_NAME='MPF_ER')
ALTER TABLE [xPayRep1] ADD [MPF_ER] [smallmoney] NULL CONSTRAINT [DF_xPayRep1_MPF_ER]  DEFAULT ((0))
