IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep2' AND COLUMN_NAME='MPF_EE')
ALTER TABLE [xPayRep2] ADD [MPF_EE] [money] NULL CONSTRAINT [DF_xPayRep2_MPF_EE]  DEFAULT ((0))

IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep2' AND COLUMN_NAME='MPF_ER')
ALTER TABLE [xPayRep2] ADD [MPF_ER] [money] NULL CONSTRAINT [DF_xPayRep2_MPF_ER]  DEFAULT ((0))
