IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep3' AND COLUMN_NAME='MPF_EE')
ALTER TABLE [xPayRep3] ADD [MPF_EE] [money] NULL CONSTRAINT [DF_xPayRep3_MPF_EE]  DEFAULT ((0))

IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep3' AND COLUMN_NAME='MPF_ER')
ALTER TABLE [xPayRep3] ADD [MPF_ER] [money] NULL CONSTRAINT [DF_xPayRep3_MPF_ER]  DEFAULT ((0))
