IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPaySlipTmp' AND COLUMN_NAME='MPF_EE')
ALTER TABLE [xPaySlipTmp] ADD [MPF_EE] [smallmoney] NULL CONSTRAINT [DF_xPaySlipTmp_MPF_EE]  DEFAULT ((0))

IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPaySlipTmp' AND COLUMN_NAME='MPF_ER')
ALTER TABLE [xPaySlipTmp] ADD [MPF_ER] [smallmoney] NULL CONSTRAINT [DF_xPaySlipTmp_MPF_ER]  DEFAULT ((0))
