IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep2' AND COLUMN_NAME='Bonus_UPH')
ALTER TABLE [xPayRep2] ADD [Bonus_UPH] [money] NULL CONSTRAINT [DF_xPayRep2_Bonus_UPH]  DEFAULT ((0))

IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep2' AND COLUMN_NAME='Bonus_Quality')
ALTER TABLE [xPayRep2] ADD [Bonus_Quality] [money] NULL CONSTRAINT [DF_xPayRep2_Bonus_Quality]  DEFAULT ((0))

IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep2' AND COLUMN_NAME='Bonus_Attendance')
ALTER TABLE [xPayRep2] ADD [Bonus_Attendance] [money] NULL CONSTRAINT [DF_xPayRep2_Bonus_Attendance]  DEFAULT ((0))

IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep2' AND COLUMN_NAME='Bonus_Retention')
ALTER TABLE [xPayRep2] ADD [Bonus_Retention] [money] NULL CONSTRAINT [DF_xPayRep2_Bonus_Retention]  DEFAULT ((0))

IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep2' AND COLUMN_NAME='SB_CashAdvance')
ALTER TABLE [xPayRep2] ADD [SB_CashAdvance] [money] NULL CONSTRAINT [DF_xPayRep2_SB_CashAdvance]  DEFAULT ((0))
