IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep2' AND COLUMN_NAME='Other_Ded1_AfterTax')
ALTER TABLE [xPayRep2] ADD [Other_Ded1_AfterTax] [money] NULL CONSTRAINT [DF_xPayRep2_Other_Ded1_AfterTax]  DEFAULT ((0))

IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep2' AND COLUMN_NAME='Other_Ded2_AfterTax')
ALTER TABLE [xPayRep2] ADD [Other_Ded2_AfterTax] [money] NULL CONSTRAINT [DF_xPayRep2_Other_Ded2_AfterTax]  DEFAULT ((0))

IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep2' AND COLUMN_NAME='Other_Ded3_AfterTax')
ALTER TABLE [xPayRep2] ADD [Other_Ded3_AfterTax] [money] NULL CONSTRAINT [DF_xPayRep2_Other_Ded3_AfterTax]  DEFAULT ((0))

IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep2' AND COLUMN_NAME='Other_Ded4_AfterTax')
ALTER TABLE [xPayRep2] ADD [Other_Ded4_AfterTax] [money] NULL CONSTRAINT [DF_xPayRep2_Other_Ded4_AfterTax]  DEFAULT ((0))

IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep2' AND COLUMN_NAME='Other_Ded5_AfterTax')
ALTER TABLE [xPayRep2] ADD [Other_Ded5_AfterTax] [money] NULL CONSTRAINT [DF_xPayRep2_Other_Ded5_AfterTax]  DEFAULT ((0))

IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep2' AND COLUMN_NAME='Other_Ded6_AfterTax')
ALTER TABLE [xPayRep2] ADD [Other_Ded6_AfterTax] [money] NULL CONSTRAINT [DF_xPayRep2_Other_Ded6_AfterTax]  DEFAULT ((0))