truncate table [dbo].[dtaBonusesDetails]
truncate table dtaDayOff
truncate table [dbo].[dtaEmpShift]
truncate table dtaHoliday_Details
truncate table [dbo].[dtaKeyerRemarks]
truncate table [dbo].[dtaLockPayPeriod]
truncate table [dbo].[dtaLogFile]
truncate table [dbo].[dtaOther_Earn_Ded]
truncate table dtaPagIbig_MP2
truncate table dtaPayrollProcess
truncate table dtaPhilhealthTable
truncate table [dbo].[dtaProduction]
truncate table dtaProjectQuality
truncate table dtaProjects
truncate table [dbo].[dtaProjectUPH]
truncate table dtaRawData
truncate table [dbo].[dtaShift]
truncate table dtaShiftDetail
truncate table dtaSSSTable
truncate table dtaTaskRemarks
truncate table dtaTaxTable
truncate table dtaTemp
truncate table dtaTime_Detail
truncate table dtaTime_Summary
truncate table dtaTimeSecurity
truncate table dtaUsers_ProjectAccess
truncate table tbl_ProcessQueue
truncate table tbl_ProcessRawDataQueue
truncate table xPayRep1
truncate table xPayRep1_Adj
truncate table xPayRep2
truncate table xPayRep3

