IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='dtaPayrollProcess' AND COLUMN_NAME='MP2_EE')
ALTER TABLE [dtaPayrollProcess] ADD [MP2_EE] [money] NULL CONSTRAINT [DF_dtaPayrollProcess_MP2_EE]  DEFAULT ((0))

IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='dtaPayrollProcess' AND COLUMN_NAME='MP2_ER')
ALTER TABLE [dtaPayrollProcess] ADD [MP2_ER] [money] NULL CONSTRAINT [DF_dtaPayrollProcess_MP2_ER]  DEFAULT ((0))