IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep1' AND COLUMN_NAME='MP2_EE')
ALTER TABLE [xPayRep1] ADD [MP2_EE] [money] NULL CONSTRAINT [DF_xPayRep1_MP2_EE]  DEFAULT ((0))

IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep1' AND COLUMN_NAME='MP2_ER')
ALTER TABLE [xPayRep1] ADD [MP2_ER] [money] NULL CONSTRAINT [DF_xPayRep1_MP2_ER]  DEFAULT ((0))

IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='xPayRep1' AND COLUMN_NAME='YTD_MP2Amount')
ALTER TABLE [xPayRep1] ADD [YTD_MP2Amount] [money] NULL CONSTRAINT [DF_xPayRep1_YTD_MP2Amount]  DEFAULT ((0))