IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='dtaEmployees' AND COLUMN_NAME='YTD_MP2Amount')
ALTER TABLE [dtaEmployees] ADD [YTD_MP2Amount] [money] NULL CONSTRAINT [DF_dtaEmployees_YTD_MP2Amount]  DEFAULT ((0))